name: deploy-server

on: 
  # Triggers the workflow on push to main 
  push:
    branches:
      - main
    # but only for any changes to auth folder or service 'auth/**''
    # Being a microservice, were projects are independent, you only want to run
    # this test when changes are made to this service, and not when changes are 
    # made to other services,
    paths:
      - 'server/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2