name: tests-client

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for any changes to client folder/service
  pull_request:
    paths:
      - 'client/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install packages
        run: cd client && npm install
      - name: Run tests
        run: CI=true && npm run test